config/routes.rb
SFLAN::Application.routes.draw do

  resources :pages

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index 
		@pages = Page.all
	end

	def show
		@page = Page.find(params[:id])
	end

	def new
	end

	def create
		@page = Page.new(page_params)

		@page.save
		redirect_to @page
	end

	private
		def page_params
			params.require(:page).permit(:title, :content)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SFLAN</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="wrapper">
			<div class="container">
				<h1>SFLAN</h1>

				<%= yield %>

			</div>
		</div>
	</body>
</html>

app/views/pages/index.html.erb
<h2>Listing Pages</h2>
<table class="table table-striped table-hover condensed">
	<thead>
		<th>Title</th>
		<th>&nbsp;</th>
	</thead>
	<tbody>
		<% @pages.each do |page| %>
			<tr>
				<td><%= page.title %></td>
				<td>&nbsp;</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/pages/new.html.erb
<h2>New Page</h2>
<%= form_for :page, html: {class: "form-horizontal"}, url: pages_path do |f| %>
	<div class="control-group">
		<%= f.label :title, :class => "control-label" %>
		<div class="controls">
			<%= f.text_field :title, :class => "input-block-level" %>
		</div>
	</div>

	<div class="control-group">
		<%= f.label :content, "Content", :class => "control-label" %>
		<div class="controls">
			<%= f.text_area :content, :class => "input-block-level", :style => "height: 300px;" %>
		</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<%= f.submit :class => "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/pages/show.html.erb
<h2><%= @page.title %></h2>
<%= @page.content %>